name: CI & CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: docker compose build

      - name: Push to DockerHub
        run: docker compose push

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup SSH Key & Deploy
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" | base64 -d > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
          
          ssh -i ~/.ssh/deploy_key $EC2_USERNAME@$EC2_HOST << 'DEPLOY_SCRIPT'
            sudo docker rm -f zenova-api || true
            sudo docker rmi -f moinaknaskar/zenova:latest || true
            sudo docker system prune -f || true
            sudo docker pull moinaknaskar/zenova:latest
            sudo docker run -d \
              -p 8000:8000 \
              --name zenova-api \
              --restart unless-stopped \
              moinaknaskar/zenova:latest
          DEPLOY_SCRIPT
